### ISSUE TITLE
Handle values that are not in the dictionary

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#202]
Currently, when we compress using a dictionary, we expect it to contain all possible value predictions (currently, `path -> (value, probability)`, or with PR #201 `probability of encountering a value recently encountered/probability of encountering a value in the global dictionary`). If we encounter a value that has no value prediction in this context, we simply cannot encode the file.

This is required for:

- property keys;
- literal strings;
- identifier names;
- numbers.

We need to find a good way to represent this.

Cc @dominiccooney, @kannanvijayan .

This issue is about extension. Issue #224 is about compression.

**Comment by Yoric** [comment]
## Letting each packet patch the dictionary

See #203 for a definition of packets. For the moment, we only have one packet.

One possible way to do this would be to let each stream packet start with a patch to the dictionary. For instance, a section `string_literals_by_window` (if we use this strategy) containing a sequence of `string literals, frequency` or `string_literals_by_path` (if we use that strategy) containing a sequence of `string literal, path, frequency`. After having read this section, the predictor `string_literals_by_*` now contains new values with frequencies.

The main drawback of that approach is that, if there are many paths, the size of a `*_by_path` section can grow a lot.

**Comment by Yoric** [comment]
## Mixed strategy

Each stream packet starts with definitions of new values, as in [the description of **Letting each packet patch the dictionary**](https://github.com/binast/binjs-ref/issues/202#issuecomment-438796618), but without any path or frequency information. Reading a new value adds it to the dictionary for the rest of the stream. However, the frequency information for the value still needs to be defined. We do this inline, using the mechanism described in [**Introducing values inline**](https://github.com/binast/binjs-ref/issues/202#issuecomment-438785604), except instead of a value, we use an index into the global dictionary.

Frequency information thus associated in the non-lazy packet is valid for the entire stream, but frequency information associated in a lazy packet is only valid for that packet.

**Comment by kannanvijayan** [comment]
I agree with the approach of letting each packet patch the dictionary - the simplest patch being: "append the following entries to the global dictionary".

But we do not need to store prediction information for newly introduced strings at all.  The performance of prediction based on window indexes performs admirably in this case.  The strategy here is to collect statistics for the following from the corpus:

1. Record each newly seen string in a fixed-size string move-to-front cache
2. Count the frequency of hits at each index in the cache.
3. Also keep a MISS count for frequency of cache misses (usually 20-40%).

The encoding strategy for string indexes is then two-fold.  During encoding/decoding we maintain the same move-to-front cache and encode hits using the probability table for indexes of the cache.

String references which do not hit the cache must be explicitly encoded.  In this case, the encoder will encode a `MISS` symbol using the cache's probability table, and then encode a raw string-table index.

These raw string table indices are typically encoded with a varuint encoding (e.g. the high bit is treated as a continuation bit, and each byte encodes 7 bits of numeric payload).  This strategy for "miss" string indices leads to an average of 12 bits per string index (averaged across all "cache-missed" string indices).

My calculations had indicated that these 12 bits/cache-missed-symbol (which account for around a quarter of string-refs when using move-to-front caching) could be reduced significantly by predicting the distinct var-uint structures:

1. Predict the length of the varuint (almost always 1 or 2, roughly 1 bit to encode).
2. For each variant (length-1, length-2, length-X), build static prediction tables for each of the constituent bytes.  This would lead to the following (6) tables (each of size 128):

  strref-0-1
  strref-0-2, strref-1-2
  strref-0-3, strref-1-3, strref-2-3

Under this scheme, the prediction tables for strref-1-2 (the high byte of a string-ref index >= 128), would show high bias towards low numbers (since high values of the high byte would be accesses deep into the strings table).

From my measurements using the typescript implementation, this approach (predicting hit-indexes into move-to-front-caches, and handling misses by predicting the components of the var-uint encodings) should reduce the cost of string-refs on average to ~4 bits per symbol.

**Comment by Yoric** [comment]
> But we do not need to store prediction information for newly introduced strings at all. The performance of prediction based on window indexes performs admirably in this case.

Filed as #209.

**Comment by Yoric** [comment]
Side-note: ideally, we should be able to introduce *any* kind of value, as an escape hatch. For instance, just because a framework from version 1.0 to 1.0.9 never uses `const` doesn't mean that it never will.

**Comment by Yoric** [comment]
Resolved in tag entropy-0.2.0.
