### ISSUE TITLE
Check compression results if we concatenate all fb files

### ISSUE THREAD

**Issue by Yoric** [binast/binjs-ref#48]
I suspect that we would get a much better result.

**Comment by Yoric** [comment]
Mmmh...

`Script error FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

**Comment by Yoric** [comment]
This should become possible once https://github.com/binast/binjs-ref/pull/69 has landed.

**Comment by sendilkumarn** [comment]
The problem now is `stack overflow` since the rust process takes a loooot of memory. It goes till `5GB` (for annotation) and running them via `cargo test` fails ( am not particularly sure whether this has any memory limit but appears to be).

For encoding, it pushes upto `6GB (~5900 - 6100 M)` and the entire process runs for almost 10-15 min. I would suggest not to have it enabled in the tests.

**Comment by Yoric** [comment]
It's a Rust stack overflow?

Yeah, if it takes 10-15 minutes, that's a bit too much.

**Comment by Yoric** [comment]
The following would help: https://github.com/binast/binjs-ref/pull/69.

**Comment by sendilkumarn** [comment]
in this case I feel we can merge #69

**Comment by Yoric** [comment]
Well, this now works.
